<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WinSpaces</RootNamespace>
    <AssemblyName>WinSpaces</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Version>0.1.5</Version>
    <Authors>WinSpaces contributors</Authors>
    <Description>macOS Spaces pour Windows — bureaux virtuels avec plein écran auto et gestes trackpad</Description>
    <Platforms>x64</Platforms>
  </PropertyGroup>

</Project>